export const GET_FON_REQUEST = "SETTINGS::GET_FON_REQUEST";
export const GET_FON_SUCCESS = "SETTINGS::GET_FON_SUCCESS";
export const GET_FON_ERROR = "SETTINGS::GET_FON_ERROR";
export const ADD_FON_FAVORITES = "SETTINGS::ADD_FON_FAVORITES";
export const ADD_FON_SETTING = "SETTINGS::ADD_FON_SETTING";
export const DELLITE_FON_FAVORITES = "SETTINGS::DELLITE_FON_FAVORITES";
export const DELLITE_FON_FULL_FAVORITES =
  "SETTINGS::DELLITE_FON_FULL_FAVORITES";
