export const ADD_MESSAGE_SAGA = "SAGA::ADD_MESSAGE_SAGA";
export const FON_SEARCH_SAGA = "SAGA::FON_SEARCH_SAGA";
export const FON_ERROR_SAGA = "SAGA::FON_ERROR_SAGA";
export const GET_FON_LOADING_SAGA = "SAGA::GET_FON_LOADING_SAGA";
