export const ADD_MESSAGE_SAGA = "SAGA::ADD_MESSAGE_SAGA";
export const FON_SEARCH_SAGA = "SAGA::FON_SEARCH_SAGA";
export const FON_ERROR_SAGA = "SAGA::FON_ERROR_SAGA";
export const GET_FON_LOADING_SAGA = "SAGA::GET_FON_LOADING_SAGA";
export const ERROR_FIREBASE_SAGA = "SAGA::ERROR_FIREBASE_SAGA"
export const CHENGE_AUTH_USER_SAGA = "SAGA::CHENGE_AUTH_USER_SAGA"
export const CHENGE_LOADING_SAGA =  "SAGA::CHENGE_LOADING_SAGA"