export const CHENGE_AUTHOR_ACTION = "PROFILE::CHENGE_AUTHOR_ACTION"
export const CHENGE_FIREBASE_NAME_ACTION = "PROFILE::CHENGE_FIREBASE_NAME_ACTION"
export const GET_FIREBASE_NAME_ACTION = "PROFILE::GET_FIREBASE_NAME_ACTION"